/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from './shared/shared.module';
import * as import7 from './core/core.module';
import * as import8 from '@angular/forms/src/directives';
import * as import9 from '@angular/forms/src/form_providers';
import * as import10 from '@angular/http/src/http_module';
import * as import11 from './home/home.module';
import * as import12 from '@angular/common/src/localization';
import * as import13 from '@angular/core/src/application_init';
import * as import14 from '@angular/core/src/testability/testability';
import * as import15 from '@angular/core/src/application_ref';
import * as import16 from '@angular/core/src/linker/compiler';
import * as import17 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import18 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import19 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import20 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import21 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import22 from '@angular/core/src/animation/animation_queue';
import * as import23 from '@angular/core/src/linker/view_utils';
import * as import24 from '@angular/platform-browser/src/browser/title';
import * as import25 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import26 from '@angular/http/src/backends/browser_xhr';
import * as import27 from '@angular/http/src/base_response_options';
import * as import28 from '@angular/http/src/backends/xhr_backend';
import * as import29 from '@angular/http/src/base_request_options';
import * as import30 from '@angular/common/src/location/location';
import * as import31 from '@angular/router/src/url_tree';
import * as import32 from '@angular/router/src/router_outlet_map';
import * as import33 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import34 from '@angular/router/src/router_preloader';
import * as import35 from './app.constants';
import * as import36 from './core/services/thing-data.service';
import * as import37 from '@angular/core/src/di/injector';
import * as import38 from './home/components/home.component.ngfactory';
import * as import39 from './app.component.ngfactory';
import * as import40 from '@angular/core/src/i18n/tokens';
import * as import41 from '@angular/core/src/application_tokens';
import * as import42 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import43 from '@angular/platform-browser/src/dom/events/key_events';
import * as import44 from '@angular/core/src/zone/ng_zone';
import * as import45 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import46 from './home/components/home.component';
import * as import47 from '@angular/common/src/location/platform_location';
import * as import48 from '@angular/common/src/location/location_strategy';
import * as import49 from '@angular/router/src/url_handling_strategy';
import * as import50 from '@angular/router/src/route_reuse_strategy';
import * as import51 from '@angular/router/src/router';
import * as import52 from '@angular/core/src/console';
import * as import53 from '@angular/core/src/error_handler';
import * as import54 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import55 from '@angular/platform-browser/src/dom/animation_driver';
import * as import56 from '@angular/core/src/render/api';
import * as import57 from '@angular/core/src/security';
import * as import58 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import59 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import60 from '@angular/http/src/interfaces';
import * as import61 from '@angular/http/src/http';
import * as import62 from '@angular/router/src/router_config_loader';
import * as import63 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import64 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _ROUTER_FORROOT_GUARD_3:any;
  _RouterModule_4:import5.RouterModule;
  _SharedModule_5:import6.SharedModule;
  _CoreModule_6:import7.CoreModule;
  _InternalFormsSharedModule_7:import8.InternalFormsSharedModule;
  _FormsModule_8:import9.FormsModule;
  _HttpModule_9:import10.HttpModule;
  _HomeModule_10:import11.HomeModule;
  _AppModule_11:import1.AppModule;
  __LOCALE_ID_12:any;
  __NgLocalization_13:import12.NgLocaleLocalization;
  _ErrorHandler_14:any;
  _RouterInitializer_15:import5.RouterInitializer;
  _APP_INITIALIZER_16:any[];
  _ApplicationInitStatus_17:import13.ApplicationInitStatus;
  _Testability_18:import14.Testability;
  _ApplicationRef__19:import15.ApplicationRef_;
  __ApplicationRef_20:any;
  __Compiler_21:import16.Compiler;
  __APP_ID_22:any;
  __DOCUMENT_23:any;
  __HAMMER_GESTURE_CONFIG_24:import17.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_25:any[];
  __EventManager_26:import18.EventManager;
  _DomSharedStylesHost_27:import19.DomSharedStylesHost;
  __AnimationDriver_28:any;
  __DomRootRenderer_29:import20.DomRootRenderer_;
  __NgProbeToken_30:any[];
  __RootRenderer_31:any;
  __DomSanitizer_32:import21.DomSanitizerImpl;
  __Sanitizer_33:any;
  __AnimationQueue_34:import22.AnimationQueue;
  __ViewUtils_35:import23.ViewUtils;
  __IterableDiffers_36:any;
  __KeyValueDiffers_37:any;
  __SharedStylesHost_38:any;
  __Title_39:import24.Title;
  __RadioControlRegistry_40:import25.RadioControlRegistry;
  __BrowserXhr_41:import26.BrowserXhr;
  __ResponseOptions_42:import27.BaseResponseOptions;
  __XSRFStrategy_43:any;
  __XHRBackend_44:import28.XHRBackend;
  __RequestOptions_45:import29.BaseRequestOptions;
  __Http_46:any;
  __ROUTES_47:any[];
  __ROUTER_CONFIGURATION_48:any;
  __LocationStrategy_49:any;
  __Location_50:import30.Location;
  __UrlSerializer_51:import31.DefaultUrlSerializer;
  __RouterOutletMap_52:import32.RouterOutletMap;
  __NgModuleFactoryLoader_53:import33.SystemJsNgModuleLoader;
  __Router_54:any;
  __ActivatedRoute_55:any;
  _NoPreloading_56:import34.NoPreloading;
  _PreloadingStrategy_57:any;
  _RouterPreloader_58:import34.RouterPreloader;
  __PreloadAllModules_59:import34.PreloadAllModules;
  __ROUTER_INITIALIZER_60:any;
  __APP_BOOTSTRAP_LISTENER_61:any[];
  __Configuration_62:import35.Configuration;
  __ThingService_63:import36.ThingService;
  constructor(parent:import37.Injector) {
    super(parent,[
      import38.HomeComponentNgFactory,
      import39.AppComponentNgFactory
    ]
    ,[import39.AppComponentNgFactory]);
  }
  get _LOCALE_ID_12():any {
    if ((this.__LOCALE_ID_12 == null)) { (this.__LOCALE_ID_12 = import3._localeFactory(this.parent.get(import40.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_12;
  }
  get _NgLocalization_13():import12.NgLocaleLocalization {
    if ((this.__NgLocalization_13 == null)) { (this.__NgLocalization_13 = new import12.NgLocaleLocalization(this._LOCALE_ID_12)); }
    return this.__NgLocalization_13;
  }
  get _ApplicationRef_20():any {
    if ((this.__ApplicationRef_20 == null)) { (this.__ApplicationRef_20 = this._ApplicationRef__19); }
    return this.__ApplicationRef_20;
  }
  get _Compiler_21():import16.Compiler {
    if ((this.__Compiler_21 == null)) { (this.__Compiler_21 = new import16.Compiler()); }
    return this.__Compiler_21;
  }
  get _APP_ID_22():any {
    if ((this.__APP_ID_22 == null)) { (this.__APP_ID_22 = import41._appIdRandomProviderFactory()); }
    return this.__APP_ID_22;
  }
  get _DOCUMENT_23():any {
    if ((this.__DOCUMENT_23 == null)) { (this.__DOCUMENT_23 = import4._document()); }
    return this.__DOCUMENT_23;
  }
  get _HAMMER_GESTURE_CONFIG_24():import17.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_24 == null)) { (this.__HAMMER_GESTURE_CONFIG_24 = new import17.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_24;
  }
  get _EVENT_MANAGER_PLUGINS_25():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_25 == null)) { (this.__EVENT_MANAGER_PLUGINS_25 = [
      new import42.DomEventsPlugin(),
      new import43.KeyEventsPlugin(),
      new import17.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_24)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_25;
  }
  get _EventManager_26():import18.EventManager {
    if ((this.__EventManager_26 == null)) { (this.__EventManager_26 = new import18.EventManager(this._EVENT_MANAGER_PLUGINS_25,this.parent.get(import44.NgZone))); }
    return this.__EventManager_26;
  }
  get _AnimationDriver_28():any {
    if ((this.__AnimationDriver_28 == null)) { (this.__AnimationDriver_28 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_28;
  }
  get _DomRootRenderer_29():import20.DomRootRenderer_ {
    if ((this.__DomRootRenderer_29 == null)) { (this.__DomRootRenderer_29 = new import20.DomRootRenderer_(this._DOCUMENT_23,this._EventManager_26,this._DomSharedStylesHost_27,this._AnimationDriver_28,this._APP_ID_22)); }
    return this.__DomRootRenderer_29;
  }
  get _NgProbeToken_30():any[] {
    if ((this.__NgProbeToken_30 == null)) { (this.__NgProbeToken_30 = [import5.routerNgProbeToken()]); }
    return this.__NgProbeToken_30;
  }
  get _RootRenderer_31():any {
    if ((this.__RootRenderer_31 == null)) { (this.__RootRenderer_31 = import45._createConditionalRootRenderer(this._DomRootRenderer_29,this.parent.get(import45.NgProbeToken,(null as any)),this._NgProbeToken_30)); }
    return this.__RootRenderer_31;
  }
  get _DomSanitizer_32():import21.DomSanitizerImpl {
    if ((this.__DomSanitizer_32 == null)) { (this.__DomSanitizer_32 = new import21.DomSanitizerImpl()); }
    return this.__DomSanitizer_32;
  }
  get _Sanitizer_33():any {
    if ((this.__Sanitizer_33 == null)) { (this.__Sanitizer_33 = this._DomSanitizer_32); }
    return this.__Sanitizer_33;
  }
  get _AnimationQueue_34():import22.AnimationQueue {
    if ((this.__AnimationQueue_34 == null)) { (this.__AnimationQueue_34 = new import22.AnimationQueue(this.parent.get(import44.NgZone))); }
    return this.__AnimationQueue_34;
  }
  get _ViewUtils_35():import23.ViewUtils {
    if ((this.__ViewUtils_35 == null)) { (this.__ViewUtils_35 = new import23.ViewUtils(this._RootRenderer_31,this._Sanitizer_33,this._AnimationQueue_34)); }
    return this.__ViewUtils_35;
  }
  get _IterableDiffers_36():any {
    if ((this.__IterableDiffers_36 == null)) { (this.__IterableDiffers_36 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_36;
  }
  get _KeyValueDiffers_37():any {
    if ((this.__KeyValueDiffers_37 == null)) { (this.__KeyValueDiffers_37 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_37;
  }
  get _SharedStylesHost_38():any {
    if ((this.__SharedStylesHost_38 == null)) { (this.__SharedStylesHost_38 = this._DomSharedStylesHost_27); }
    return this.__SharedStylesHost_38;
  }
  get _Title_39():import24.Title {
    if ((this.__Title_39 == null)) { (this.__Title_39 = new import24.Title()); }
    return this.__Title_39;
  }
  get _RadioControlRegistry_40():import25.RadioControlRegistry {
    if ((this.__RadioControlRegistry_40 == null)) { (this.__RadioControlRegistry_40 = new import25.RadioControlRegistry()); }
    return this.__RadioControlRegistry_40;
  }
  get _BrowserXhr_41():import26.BrowserXhr {
    if ((this.__BrowserXhr_41 == null)) { (this.__BrowserXhr_41 = new import26.BrowserXhr()); }
    return this.__BrowserXhr_41;
  }
  get _ResponseOptions_42():import27.BaseResponseOptions {
    if ((this.__ResponseOptions_42 == null)) { (this.__ResponseOptions_42 = new import27.BaseResponseOptions()); }
    return this.__ResponseOptions_42;
  }
  get _XSRFStrategy_43():any {
    if ((this.__XSRFStrategy_43 == null)) { (this.__XSRFStrategy_43 = import10._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_43;
  }
  get _XHRBackend_44():import28.XHRBackend {
    if ((this.__XHRBackend_44 == null)) { (this.__XHRBackend_44 = new import28.XHRBackend(this._BrowserXhr_41,this._ResponseOptions_42,this._XSRFStrategy_43)); }
    return this.__XHRBackend_44;
  }
  get _RequestOptions_45():import29.BaseRequestOptions {
    if ((this.__RequestOptions_45 == null)) { (this.__RequestOptions_45 = new import29.BaseRequestOptions()); }
    return this.__RequestOptions_45;
  }
  get _Http_46():any {
    if ((this.__Http_46 == null)) { (this.__Http_46 = import10.httpFactory(this._XHRBackend_44,this._RequestOptions_45)); }
    return this.__Http_46;
  }
  get _ROUTES_47():any[] {
    if ((this.__ROUTES_47 == null)) { (this.__ROUTES_47 = [
        [{
          path: 'home',
          component: import46.HomeComponent
        }
      ],
      [
        {
          path: '',
          redirectTo: 'home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'about',
          loadChildren: './about/about.module#AboutModule'
        }

      ]

    ]
    ); }
    return this.__ROUTES_47;
  }
  get _ROUTER_CONFIGURATION_48():any {
    if ((this.__ROUTER_CONFIGURATION_48 == null)) { (this.__ROUTER_CONFIGURATION_48 = {}); }
    return this.__ROUTER_CONFIGURATION_48;
  }
  get _LocationStrategy_49():any {
    if ((this.__LocationStrategy_49 == null)) { (this.__LocationStrategy_49 = import5.provideLocationStrategy(this.parent.get(import47.PlatformLocation),this.parent.get(import48.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_48)); }
    return this.__LocationStrategy_49;
  }
  get _Location_50():import30.Location {
    if ((this.__Location_50 == null)) { (this.__Location_50 = new import30.Location(this._LocationStrategy_49)); }
    return this.__Location_50;
  }
  get _UrlSerializer_51():import31.DefaultUrlSerializer {
    if ((this.__UrlSerializer_51 == null)) { (this.__UrlSerializer_51 = new import31.DefaultUrlSerializer()); }
    return this.__UrlSerializer_51;
  }
  get _RouterOutletMap_52():import32.RouterOutletMap {
    if ((this.__RouterOutletMap_52 == null)) { (this.__RouterOutletMap_52 = new import32.RouterOutletMap()); }
    return this.__RouterOutletMap_52;
  }
  get _NgModuleFactoryLoader_53():import33.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_53 == null)) { (this.__NgModuleFactoryLoader_53 = new import33.SystemJsNgModuleLoader(this._Compiler_21,this.parent.get(import33.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_53;
  }
  get _Router_54():any {
    if ((this.__Router_54 == null)) { (this.__Router_54 = import5.setupRouter(this._ApplicationRef_20,this._UrlSerializer_51,this._RouterOutletMap_52,this._Location_50,this,this._NgModuleFactoryLoader_53,this._Compiler_21,this._ROUTES_47,this._ROUTER_CONFIGURATION_48,this.parent.get(import49.UrlHandlingStrategy,(null as any)),this.parent.get(import50.RouteReuseStrategy,(null as any)))); }
    return this.__Router_54;
  }
  get _ActivatedRoute_55():any {
    if ((this.__ActivatedRoute_55 == null)) { (this.__ActivatedRoute_55 = import5.rootRoute(this._Router_54)); }
    return this.__ActivatedRoute_55;
  }
  get _PreloadAllModules_59():import34.PreloadAllModules {
    if ((this.__PreloadAllModules_59 == null)) { (this.__PreloadAllModules_59 = new import34.PreloadAllModules()); }
    return this.__PreloadAllModules_59;
  }
  get _ROUTER_INITIALIZER_60():any {
    if ((this.__ROUTER_INITIALIZER_60 == null)) { (this.__ROUTER_INITIALIZER_60 = import5.getBootstrapListener(this._RouterInitializer_15)); }
    return this.__ROUTER_INITIALIZER_60;
  }
  get _APP_BOOTSTRAP_LISTENER_61():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_61 == null)) { (this.__APP_BOOTSTRAP_LISTENER_61 = [this._ROUTER_INITIALIZER_60]); }
    return this.__APP_BOOTSTRAP_LISTENER_61;
  }
  get _Configuration_62():import35.Configuration {
    if ((this.__Configuration_62 == null)) { (this.__Configuration_62 = new import35.Configuration()); }
    return this.__Configuration_62;
  }
  get _ThingService_63():import36.ThingService {
    if ((this.__ThingService_63 == null)) { (this.__ThingService_63 = new import36.ThingService(this._Http_46,this._Configuration_62)); }
    return this.__ThingService_63;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_3 = import5.provideForRootGuard(this.parent.get(import51.Router,(null as any)));
    this._RouterModule_4 = new import5.RouterModule(this._ROUTER_FORROOT_GUARD_3);
    this._SharedModule_5 = new import6.SharedModule();
    this._CoreModule_6 = new import7.CoreModule();
    this._InternalFormsSharedModule_7 = new import8.InternalFormsSharedModule();
    this._FormsModule_8 = new import9.FormsModule();
    this._HttpModule_9 = new import10.HttpModule();
    this._HomeModule_10 = new import11.HomeModule();
    this._AppModule_11 = new import1.AppModule();
    this._ErrorHandler_14 = import4.errorHandler();
    this._RouterInitializer_15 = new import5.RouterInitializer(this);
    this._APP_INITIALIZER_16 = [import5.getAppInitializer(this._RouterInitializer_15)];
    this._ApplicationInitStatus_17 = new import13.ApplicationInitStatus(this._APP_INITIALIZER_16);
    this._Testability_18 = new import14.Testability(this.parent.get(import44.NgZone));
    this._ApplicationRef__19 = new import15.ApplicationRef_(this.parent.get(import44.NgZone),this.parent.get(import52.Console),this,this._ErrorHandler_14,this,this._ApplicationInitStatus_17,this.parent.get(import14.TestabilityRegistry,(null as any)),this._Testability_18);
    this._DomSharedStylesHost_27 = new import19.DomSharedStylesHost(this._DOCUMENT_23);
    this._NoPreloading_56 = new import34.NoPreloading();
    this._PreloadingStrategy_57 = this._NoPreloading_56;
    this._RouterPreloader_58 = new import34.RouterPreloader(this._Router_54,this._NgModuleFactoryLoader_53,this._Compiler_21,this,this._PreloadingStrategy_57);
    return this._AppModule_11;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_3; }
    if ((token === import5.RouterModule)) { return this._RouterModule_4; }
    if ((token === import6.SharedModule)) { return this._SharedModule_5; }
    if ((token === import7.CoreModule)) { return this._CoreModule_6; }
    if ((token === import8.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_7; }
    if ((token === import9.FormsModule)) { return this._FormsModule_8; }
    if ((token === import10.HttpModule)) { return this._HttpModule_9; }
    if ((token === import11.HomeModule)) { return this._HomeModule_10; }
    if ((token === import1.AppModule)) { return this._AppModule_11; }
    if ((token === import40.LOCALE_ID)) { return this._LOCALE_ID_12; }
    if ((token === import12.NgLocalization)) { return this._NgLocalization_13; }
    if ((token === import53.ErrorHandler)) { return this._ErrorHandler_14; }
    if ((token === import5.RouterInitializer)) { return this._RouterInitializer_15; }
    if ((token === import13.APP_INITIALIZER)) { return this._APP_INITIALIZER_16; }
    if ((token === import13.ApplicationInitStatus)) { return this._ApplicationInitStatus_17; }
    if ((token === import14.Testability)) { return this._Testability_18; }
    if ((token === import15.ApplicationRef_)) { return this._ApplicationRef__19; }
    if ((token === import15.ApplicationRef)) { return this._ApplicationRef_20; }
    if ((token === import16.Compiler)) { return this._Compiler_21; }
    if ((token === import41.APP_ID)) { return this._APP_ID_22; }
    if ((token === import54.DOCUMENT)) { return this._DOCUMENT_23; }
    if ((token === import17.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_24; }
    if ((token === import18.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_25; }
    if ((token === import18.EventManager)) { return this._EventManager_26; }
    if ((token === import19.DomSharedStylesHost)) { return this._DomSharedStylesHost_27; }
    if ((token === import55.AnimationDriver)) { return this._AnimationDriver_28; }
    if ((token === import20.DomRootRenderer)) { return this._DomRootRenderer_29; }
    if ((token === import15.NgProbeToken)) { return this._NgProbeToken_30; }
    if ((token === import56.RootRenderer)) { return this._RootRenderer_31; }
    if ((token === import21.DomSanitizer)) { return this._DomSanitizer_32; }
    if ((token === import57.Sanitizer)) { return this._Sanitizer_33; }
    if ((token === import22.AnimationQueue)) { return this._AnimationQueue_34; }
    if ((token === import23.ViewUtils)) { return this._ViewUtils_35; }
    if ((token === import58.IterableDiffers)) { return this._IterableDiffers_36; }
    if ((token === import59.KeyValueDiffers)) { return this._KeyValueDiffers_37; }
    if ((token === import19.SharedStylesHost)) { return this._SharedStylesHost_38; }
    if ((token === import24.Title)) { return this._Title_39; }
    if ((token === import25.RadioControlRegistry)) { return this._RadioControlRegistry_40; }
    if ((token === import26.BrowserXhr)) { return this._BrowserXhr_41; }
    if ((token === import27.ResponseOptions)) { return this._ResponseOptions_42; }
    if ((token === import60.XSRFStrategy)) { return this._XSRFStrategy_43; }
    if ((token === import28.XHRBackend)) { return this._XHRBackend_44; }
    if ((token === import29.RequestOptions)) { return this._RequestOptions_45; }
    if ((token === import61.Http)) { return this._Http_46; }
    if ((token === import62.ROUTES)) { return this._ROUTES_47; }
    if ((token === import5.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_48; }
    if ((token === import48.LocationStrategy)) { return this._LocationStrategy_49; }
    if ((token === import30.Location)) { return this._Location_50; }
    if ((token === import31.UrlSerializer)) { return this._UrlSerializer_51; }
    if ((token === import32.RouterOutletMap)) { return this._RouterOutletMap_52; }
    if ((token === import63.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_53; }
    if ((token === import51.Router)) { return this._Router_54; }
    if ((token === import64.ActivatedRoute)) { return this._ActivatedRoute_55; }
    if ((token === import34.NoPreloading)) { return this._NoPreloading_56; }
    if ((token === import34.PreloadingStrategy)) { return this._PreloadingStrategy_57; }
    if ((token === import34.RouterPreloader)) { return this._RouterPreloader_58; }
    if ((token === import34.PreloadAllModules)) { return this._PreloadAllModules_59; }
    if ((token === import5.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_60; }
    if ((token === import41.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_61; }
    if ((token === import35.Configuration)) { return this._Configuration_62; }
    if ((token === import36.ThingService)) { return this._ThingService_63; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__19.ngOnDestroy();
    this._DomSharedStylesHost_27.ngOnDestroy();
    this._RouterPreloader_58.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);