/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './home.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/router/src/router_module';
import * as import7 from '@angular/common/src/localization';
import * as import8 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import9 from '@angular/http/src/backends/browser_xhr';
import * as import10 from '@angular/http/src/base_response_options';
import * as import11 from '@angular/http/src/backends/xhr_backend';
import * as import12 from '@angular/http/src/base_request_options';
import * as import13 from '@angular/core/src/di/injector';
import * as import14 from './components/home.component.ngfactory';
import * as import15 from '@angular/core/src/i18n/tokens';
import * as import16 from './components/home.component';
import * as import17 from '@angular/http/src/interfaces';
import * as import18 from '@angular/http/src/http';
import * as import19 from '@angular/router/src/router_config_loader';
class HomeModuleInjector extends import0.NgModuleInjector<import1.HomeModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _HttpModule_3:import5.HttpModule;
  _RouterModule_4:import6.RouterModule;
  _HomeModule_5:import1.HomeModule;
  __NgLocalization_6:import7.NgLocaleLocalization;
  __RadioControlRegistry_7:import8.RadioControlRegistry;
  __BrowserXhr_8:import9.BrowserXhr;
  __ResponseOptions_9:import10.BaseResponseOptions;
  __XSRFStrategy_10:any;
  __XHRBackend_11:import11.XHRBackend;
  __RequestOptions_12:import12.BaseRequestOptions;
  __Http_13:any;
  __ROUTES_14:any[];
  constructor(parent:import13.Injector) {
    super(parent,[import14.HomeComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_6():import7.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == null)) { (this.__NgLocalization_6 = new import7.NgLocaleLocalization(this.parent.get(import15.LOCALE_ID))); }
    return this.__NgLocalization_6;
  }
  get _RadioControlRegistry_7():import8.RadioControlRegistry {
    if ((this.__RadioControlRegistry_7 == null)) { (this.__RadioControlRegistry_7 = new import8.RadioControlRegistry()); }
    return this.__RadioControlRegistry_7;
  }
  get _BrowserXhr_8():import9.BrowserXhr {
    if ((this.__BrowserXhr_8 == null)) { (this.__BrowserXhr_8 = new import9.BrowserXhr()); }
    return this.__BrowserXhr_8;
  }
  get _ResponseOptions_9():import10.BaseResponseOptions {
    if ((this.__ResponseOptions_9 == null)) { (this.__ResponseOptions_9 = new import10.BaseResponseOptions()); }
    return this.__ResponseOptions_9;
  }
  get _XSRFStrategy_10():any {
    if ((this.__XSRFStrategy_10 == null)) { (this.__XSRFStrategy_10 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_10;
  }
  get _XHRBackend_11():import11.XHRBackend {
    if ((this.__XHRBackend_11 == null)) { (this.__XHRBackend_11 = new import11.XHRBackend(this._BrowserXhr_8,this._ResponseOptions_9,this._XSRFStrategy_10)); }
    return this.__XHRBackend_11;
  }
  get _RequestOptions_12():import12.BaseRequestOptions {
    if ((this.__RequestOptions_12 == null)) { (this.__RequestOptions_12 = new import12.BaseRequestOptions()); }
    return this.__RequestOptions_12;
  }
  get _Http_13():any {
    if ((this.__Http_13 == null)) { (this.__Http_13 = import5.httpFactory(this._XHRBackend_11,this._RequestOptions_12)); }
    return this.__Http_13;
  }
  get _ROUTES_14():any[] {
        if ((this.__ROUTES_14 == null)) { (this.__ROUTES_14 = [[{
          path: 'home',
          component: import16.HomeComponent
        }
    ]]); }
    return this.__ROUTES_14;
  }
  createInternal():import1.HomeModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._HttpModule_3 = new import5.HttpModule();
    this._RouterModule_4 = new import6.RouterModule(this.parent.get(import6.ROUTER_FORROOT_GUARD,(null as any)));
    this._HomeModule_5 = new import1.HomeModule();
    return this._HomeModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.RouterModule)) { return this._RouterModule_4; }
    if ((token === import1.HomeModule)) { return this._HomeModule_5; }
    if ((token === import7.NgLocalization)) { return this._NgLocalization_6; }
    if ((token === import8.RadioControlRegistry)) { return this._RadioControlRegistry_7; }
    if ((token === import9.BrowserXhr)) { return this._BrowserXhr_8; }
    if ((token === import10.ResponseOptions)) { return this._ResponseOptions_9; }
    if ((token === import17.XSRFStrategy)) { return this._XSRFStrategy_10; }
    if ((token === import11.XHRBackend)) { return this._XHRBackend_11; }
    if ((token === import12.RequestOptions)) { return this._RequestOptions_12; }
    if ((token === import18.Http)) { return this._Http_13; }
    if ((token === import19.ROUTES)) { return this._ROUTES_14; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const HomeModuleNgFactory:import0.NgModuleFactory<import1.HomeModule> = new import0.NgModuleFactory(HomeModuleInjector,import1.HomeModule);