/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './navigation.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '@angular/common/src/location/location_strategy';
import * as import12 from '@angular/router/src/directives/router_link';
export class Wrapper_NavigationComponent {
  /*private*/ _eventHandler:Function;
  context:import0.NavigationComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.NavigationComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_NavigationComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_NavigationComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.NavigationComponent>;
  _NavigationComponent_0_3:Wrapper_NavigationComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NavigationComponent_Host0,renderType_NavigationComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'navigation',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_NavigationComponent0(this.viewUtils,this,0,this._el_0);
    this._NavigationComponent_0_3 = new Wrapper_NavigationComponent();
    this.compView_0.create(this._NavigationComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._NavigationComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.NavigationComponent) && (0 === requestNodeIndex))) { return this._NavigationComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NavigationComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const NavigationComponentNgFactory:import7.ComponentFactory<import0.NavigationComponent> = new import7.ComponentFactory<import0.NavigationComponent>('navigation',View_NavigationComponent_Host0,import0.NavigationComponent);
const styles_NavigationComponent:any[] = ([] as any[]);
var renderType_NavigationComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_NavigationComponent,{});
export class View_NavigationComponent0 extends import1.AppView<import0.NavigationComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _RouterLinkWithHref_18_3:import8.Wrapper_RouterLinkWithHref;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _RouterLinkWithHref_28_3:import8.Wrapper_RouterLinkWithHref;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _el_32:any;
  _RouterLinkWithHref_32_3:import8.Wrapper_RouterLinkWithHref;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _arr_62:any;
  _arr_63:any;
  _arr_64:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NavigationComponent0,renderType_NavigationComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._arr_62 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_63 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_64 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'nav',new import3.InlineArray2(2,'class','navbar navbar-inverse navbar-fixed-top'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'button',new import3.InlineArray16(12,'aria-controls','navbar','aria-expanded','false','class','navbar-toggle collapsed','data-target','#navbar','data-toggle','collapse','type','button'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Toggle navigation',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_6,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_12 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_6,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_14 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_6,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_4,'a',new import3.InlineArray2(2,'class','navbar-brand'),(null as any));
    this._RouterLinkWithHref_18_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import10.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import11.LocationStrategy,this.parentIndex));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_18,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'ASP.NET Core Angular Webpack',(null as any));
    this._text_21 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','collapse navbar-collapse','id','navbar'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'ul',new import3.InlineArray2(2,'class','nav navbar-nav'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_27,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_28_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import10.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import11.LocationStrategy,this.parentIndex));
    this._text_29 = this.renderer.createText(this._el_28,'Home',(null as any));
    this._text_30 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_25,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_31,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_32_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import10.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import11.LocationStrategy,this.parentIndex));
    this._text_33 = this.renderer.createText(this._el_32,'About',(null as any));
    this._text_34 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._text_35 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_23,'ul',new import3.InlineArray2(2,'class','nav navbar-nav navbar-right'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n                    ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_40,'img',new import3.InlineArray4(4,'height','30','src',''),(null as any));
    this._text_42 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._text_43 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_36,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n                    ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_44,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_46,'img',new import3.InlineArray4(4,'height','30','src',''),(null as any));
    this._text_48 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._text_49 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_36,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n                    ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_52,'img',new import3.InlineArray4(4,'height','30','src',''),(null as any));
    this._text_54 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._text_55 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._text_56 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._text_57 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_58 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_28));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_32,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_32));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.RouterLinkWithHref) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_18_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._RouterLinkWithHref_28_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._RouterLinkWithHref_32_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_18_0_0:any = this._arr_62('/home');
    this._RouterLinkWithHref_18_3.check_routerLink(currVal_18_0_0,throwOnChange,false);
    this._RouterLinkWithHref_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_28_0_0:any = this._arr_63('/home');
    this._RouterLinkWithHref_28_3.check_routerLink(currVal_28_0_0,throwOnChange,false);
    this._RouterLinkWithHref_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_32_0_0:any = this._arr_64('/about');
    this._RouterLinkWithHref_32_3.check_routerLink(currVal_32_0_0,throwOnChange,false);
    this._RouterLinkWithHref_32_3.ngDoCheck(this,this._el_32,throwOnChange);
    this._RouterLinkWithHref_18_3.checkHost(this,this,this._el_18,throwOnChange);
    this._RouterLinkWithHref_28_3.checkHost(this,this,this._el_28,throwOnChange);
    this._RouterLinkWithHref_32_3.checkHost(this,this,this._el_32,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_18_3.ngOnDestroy();
    this._RouterLinkWithHref_28_3.ngOnDestroy();
    this._RouterLinkWithHref_32_3.ngOnDestroy();
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_28_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_32(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_32_3.handleEvent(eventName,$event) && result);
    return result;
  }
}